[workspace]
members = ["."]

[package]
name = "gnss-time-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.gnss-time]
path = ".."

[[bin]]
name = "fuzz_gps_utc"
path = "fuzz_targets/fuzz_gps_utc.rs"
test = false
doc = false
bench = false

# Release profile: keep debug info for better crash reports
[profile.release]
debug = true
