[package]
name = "gnss-time-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[[bin]]
bench = false
doc = false
name = "fuzz_gps_utc"
path = "fuzz_targets/fuzz_gps_utc.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_week_tow"
path = "fuzz_targets/fuzz_week_tow.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_day_tod"
path = "fuzz_targets/fuzz_day_tod.rs"
test = false

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.gnss-time]
path = ".."

# Release profile: keep debug info for better crash reports
[profile.release]
debug = true
